#!/bin/bash

export DISPLAY=":0.0"
I3_WORKSPACE_BROWSER=2
I3_WORKSPACE_FEH=5
I3_WORKSPACE_KODI=3
FEH_CURRENT_FILE="/tmp/feh.current"
FEH_SLIDESHOW_DELAY=30
FEH_SLIDESHOW_PID="/tmp/feh.pid"
PICTURE_DELETE_PATH="/mnt/photos/_deleted"
PICTURE_EXCLUDE_PATH="/mnt/photos/other_photos"
PICTURE_TAG_PRIVATE="private"
PICTURE_TAG_FAVORITE="favorite"
#AMP_HDMI_X11_IGNORE="SONY"
AMP_HDMI_X11_IGNORE="RX-V1700"
MUSIC_PATH="/mnt/music"
MUSIC_PLAYLIST_PATH="/mnt/playlists"
TOUCH_MONITOR="Acer T232HL"
AMP_HDMI_DETECTED_FILE="/tmp/amp.hdmi.detected"
