__author__ = 'dcristian'

SIGNAL_SENSOR = 'signal-from-sensor'
SIGNAL_SENSOR_DB_POST = 'signal-from-db-post'

ERROR_CONNECT_MAX_RETRY_COUNT = 10
ERROR_CONNECT_PAUSE_SECOND = 1
OS = 'not initialised'
OS_LINUX='Linux'
OS_WINDOWS={'Windows', 'nt'}

SCRIPT_RESPONSE_OK='RESULTOK'

PARAM_MZP_SERVER_URL='MZP_SERVER_URL'
PARAM_MQTT_HOST='MQTT_HOST'
PARAM_OWSERVER_HOST_1='OWSERVER_HOST_1'

