__author__ = 'dcristian'

NODE_THIS_IS_MASTER_OVERALL = False
NODE_THIS_IS_MASTER_GRAPH = False
NODE_THIS_IS_MASTER_DB_ARCHIVE = False
NODE_THIS_IS_MASTER_RULE = False
NODE_THIS_IS_MASTER_LOGGING = False

USB_PORTS_IN_USE = []
